name: 'ZC Webform Paragraph'
description: 'Installs Zoocha Webform Paragraph Component'
type: 'Feature'
install:
  - webform
recipes:
  - zr-paragraph-bundle
  - zr-webform-bundle

config:
  strict: false
